name: SMS Spam Detection Action
description: 'SMS Spam Detection Action enables a user to check if any given message is a `spam` or a `ham`'
author: 'Amaan Iqbal'
branding:
  icon: 'activity'
  color: 'green'
inputs:
  message:
    description: 'Message to be checked for spam'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
